---
title: "Citibike Data Monthly"
author: "Jana Choe"
date: "2026-02-19"
output:
  pdf_document: default
  html_document: default
---
```{r}
library(tidyverse)
library(lubridate)
citibike_sum <- read.csv(file = "~/Downloads/citibike_summary_2023.csv", header = T)
```
```{r}
monthly_sum <- citibike_sum %>%
  separate(date, into = c("month", "day"), sep = "-", convert = TRUE) %>%
  group_by(month) %>%
  summarise(
    total_trips = sum(trips),
    total_time = sum(total_time),

    # weighted average trip time
    avg_time = sum(avg_time * trips) / sum(trips),

    # weighted percentages
    member_pct = sum(member_percent * trips) / sum(trips),
    casual_pct = sum(casual_percent * trips) / sum(trips),

    ebike_pct = sum(ebike_percent * trips) / sum(trips),
    regular_pct = sum(regular_percent * trips) / sum(trips)
  )

tail(monthly_sum)

```
Average Trip Duration by month
```{r}
gg1 <- ggplot(monthly_sum, aes(x = factor(month), y = avg_time)) +
  geom_col(fill = "lightblue", alpha = 0.8) +
  geom_line(aes(group = 1), color = "black", linewidth = 1) +
  geom_point(color = "black", linewidth = 2) +
  scale_x_discrete(labels = month.abb) +  
  labs(
    title = "Average Trip Duration by Month",
    x = "Month",
    y = "Min"
  ) +
  theme_minimal()

gg1
```
```{r}
monthly_bike <- monthly_sum %>%
  select(month, ebike_pct, regular_pct) %>%
  pivot_longer(-month, names_to = "bike_type", values_to = "pct")

gg_bike <- ggplot(monthly_bike, aes(x = factor(month), y = pct, fill = bike_type)) +
  geom_col(position = "dodge", alpha = 0.8) +
  geom_line(aes(group = bike_type, color = bike_type), linewidth = 1) +
  geom_point(aes(color = bike_type), linewidth = 2) +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  scale_x_discrete(labels = month.abb) +
  labs(
    title = "E-bike vs Regular Share by Month",
    x = "Month",
    y = "Percent",
    fill = "Bike Type",
    color = "Bike Type"
  ) +
  theme_minimal()

gg_bike
```
```{r}
monthly_member <- monthly_sum %>%
  select(month, member_pct, casual_pct) %>%
  pivot_longer(-month, names_to = "user_type", values_to = "pct")

gg_mem <- ggplot(monthly_member, aes(x = factor(month), y = pct, fill = user_type)) +
  geom_col(position = "dodge", alpha = 0.8) +
  geom_line(aes(group = user_type, color = user_type), linewidth = 1) +
  geom_point(aes(color = user_type),linewidth = 2) +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  scale_x_discrete(labels = month.abb) +
  labs(
    title = "Member vs Nonmember distribution by Month",
    x = "Month",
    y = "Percent"
  ) +
  theme_minimal()

gg_mem
```